// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: abi/v1/commands.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum values are prefixed with their enum name because proto3 scopes them to
// the enclosing package, not to the enum: without the prefix, two enums in this
// file could not both declare an UNSPECIFIED value. Only the numbers are the
// contract, so renaming a value is wire-compatible.
type CommandNodeKind int32

const (
	CommandNodeKind_COMMAND_NODE_KIND_UNSPECIFIED CommandNodeKind = 0
	CommandNodeKind_COMMAND_NODE_KIND_LITERAL     CommandNodeKind = 1
	CommandNodeKind_COMMAND_NODE_KIND_ARGUMENT    CommandNodeKind = 2
)

// Enum value maps for CommandNodeKind.
var (
	CommandNodeKind_name = map[int32]string{
		0: "COMMAND_NODE_KIND_UNSPECIFIED",
		1: "COMMAND_NODE_KIND_LITERAL",
		2: "COMMAND_NODE_KIND_ARGUMENT",
	}
	CommandNodeKind_value = map[string]int32{
		"COMMAND_NODE_KIND_UNSPECIFIED": 0,
		"COMMAND_NODE_KIND_LITERAL":     1,
		"COMMAND_NODE_KIND_ARGUMENT":    2,
	}
)

func (x CommandNodeKind) Enum() *CommandNodeKind {
	p := new(CommandNodeKind)
	*p = x
	return p
}

func (x CommandNodeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandNodeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_abi_v1_commands_proto_enumTypes[0].Descriptor()
}

func (CommandNodeKind) Type() protoreflect.EnumType {
	return &file_abi_v1_commands_proto_enumTypes[0]
}

func (x CommandNodeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandNodeKind.Descriptor instead.
func (CommandNodeKind) EnumDescriptor() ([]byte, []int) {
	return file_abi_v1_commands_proto_rawDescGZIP(), []int{0}
}

type CommandArgumentType int32

const (
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_UNSPECIFIED CommandArgumentType = 0
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_INTEGER     CommandArgumentType = 1
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_DECIMAL     CommandArgumentType = 2
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_STRING      CommandArgumentType = 3
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_GREEDY      CommandArgumentType = 4
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_PLAYER      CommandArgumentType = 5
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_BLOCK_POS   CommandArgumentType = 6
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_BLOCK_STATE CommandArgumentType = 7
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_ITEM        CommandArgumentType = 8
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_DURATION    CommandArgumentType = 9
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_ENUM        CommandArgumentType = 10
	CommandArgumentType_COMMAND_ARGUMENT_TYPE_CUSTOM      CommandArgumentType = 11
)

// Enum value maps for CommandArgumentType.
var (
	CommandArgumentType_name = map[int32]string{
		0:  "COMMAND_ARGUMENT_TYPE_UNSPECIFIED",
		1:  "COMMAND_ARGUMENT_TYPE_INTEGER",
		2:  "COMMAND_ARGUMENT_TYPE_DECIMAL",
		3:  "COMMAND_ARGUMENT_TYPE_STRING",
		4:  "COMMAND_ARGUMENT_TYPE_GREEDY",
		5:  "COMMAND_ARGUMENT_TYPE_PLAYER",
		6:  "COMMAND_ARGUMENT_TYPE_BLOCK_POS",
		7:  "COMMAND_ARGUMENT_TYPE_BLOCK_STATE",
		8:  "COMMAND_ARGUMENT_TYPE_ITEM",
		9:  "COMMAND_ARGUMENT_TYPE_DURATION",
		10: "COMMAND_ARGUMENT_TYPE_ENUM",
		11: "COMMAND_ARGUMENT_TYPE_CUSTOM",
	}
	CommandArgumentType_value = map[string]int32{
		"COMMAND_ARGUMENT_TYPE_UNSPECIFIED": 0,
		"COMMAND_ARGUMENT_TYPE_INTEGER":     1,
		"COMMAND_ARGUMENT_TYPE_DECIMAL":     2,
		"COMMAND_ARGUMENT_TYPE_STRING":      3,
		"COMMAND_ARGUMENT_TYPE_GREEDY":      4,
		"COMMAND_ARGUMENT_TYPE_PLAYER":      5,
		"COMMAND_ARGUMENT_TYPE_BLOCK_POS":   6,
		"COMMAND_ARGUMENT_TYPE_BLOCK_STATE": 7,
		"COMMAND_ARGUMENT_TYPE_ITEM":        8,
		"COMMAND_ARGUMENT_TYPE_DURATION":    9,
		"COMMAND_ARGUMENT_TYPE_ENUM":        10,
		"COMMAND_ARGUMENT_TYPE_CUSTOM":      11,
	}
)

func (x CommandArgumentType) Enum() *CommandArgumentType {
	p := new(CommandArgumentType)
	*p = x
	return p
}

func (x CommandArgumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandArgumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_abi_v1_commands_proto_enumTypes[1].Descriptor()
}

func (CommandArgumentType) Type() protoreflect.EnumType {
	return &file_abi_v1_commands_proto_enumTypes[1]
}

func (x CommandArgumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandArgumentType.Descriptor instead.
func (CommandArgumentType) EnumDescriptor() ([]byte, []int) {
	return file_abi_v1_commands_proto_rawDescGZIP(), []int{1}
}

type CommandTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Children      []*CommandNode         `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandTree) Reset() {
	*x = CommandTree{}
	mi := &file_abi_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandTree) ProtoMessage() {}

func (x *CommandTree) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandTree.ProtoReflect.Descriptor instead.
func (*CommandTree) Descriptor() ([]byte, []int) {
	return file_abi_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *CommandTree) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CommandTree) GetChildren() []*CommandNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type CommandNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CommandNodeKind        `protobuf:"varint,1,opt,name=kind,proto3,enum=gocraft.abi.v1.CommandNodeKind" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	ArgumentType  CommandArgumentType    `protobuf:"varint,4,opt,name=argument_type,json=argumentType,proto3,enum=gocraft.abi.v1.CommandArgumentType" json:"argument_type,omitempty"`
	EnumValues    []string               `protobuf:"bytes,5,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	Executor      uint32                 `protobuf:"varint,6,opt,name=executor,proto3" json:"executor,omitempty"`
	Children      []*CommandNode         `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	CustomType    string                 `protobuf:"bytes,8,opt,name=custom_type,json=customType,proto3" json:"custom_type,omitempty"`
	IntegerMin    *int64                 `protobuf:"zigzag64,9,opt,name=integer_min,json=integerMin,proto3,oneof" json:"integer_min,omitempty"`
	IntegerMax    *int64                 `protobuf:"zigzag64,10,opt,name=integer_max,json=integerMax,proto3,oneof" json:"integer_max,omitempty"`
	DecimalMin    *float64               `protobuf:"fixed64,11,opt,name=decimal_min,json=decimalMin,proto3,oneof" json:"decimal_min,omitempty"`
	DecimalMax    *float64               `protobuf:"fixed64,12,opt,name=decimal_max,json=decimalMax,proto3,oneof" json:"decimal_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandNode) Reset() {
	*x = CommandNode{}
	mi := &file_abi_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandNode) ProtoMessage() {}

func (x *CommandNode) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandNode.ProtoReflect.Descriptor instead.
func (*CommandNode) Descriptor() ([]byte, []int) {
	return file_abi_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CommandNode) GetKind() CommandNodeKind {
	if x != nil {
		return x.Kind
	}
	return CommandNodeKind_COMMAND_NODE_KIND_UNSPECIFIED
}

func (x *CommandNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandNode) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *CommandNode) GetArgumentType() CommandArgumentType {
	if x != nil {
		return x.ArgumentType
	}
	return CommandArgumentType_COMMAND_ARGUMENT_TYPE_UNSPECIFIED
}

func (x *CommandNode) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *CommandNode) GetExecutor() uint32 {
	if x != nil {
		return x.Executor
	}
	return 0
}

func (x *CommandNode) GetChildren() []*CommandNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *CommandNode) GetCustomType() string {
	if x != nil {
		return x.CustomType
	}
	return ""
}

func (x *CommandNode) GetIntegerMin() int64 {
	if x != nil && x.IntegerMin != nil {
		return *x.IntegerMin
	}
	return 0
}

func (x *CommandNode) GetIntegerMax() int64 {
	if x != nil && x.IntegerMax != nil {
		return *x.IntegerMax
	}
	return 0
}

func (x *CommandNode) GetDecimalMin() float64 {
	if x != nil && x.DecimalMin != nil {
		return *x.DecimalMin
	}
	return 0
}

func (x *CommandNode) GetDecimalMax() float64 {
	if x != nil && x.DecimalMax != nil {
		return *x.DecimalMax
	}
	return 0
}

var File_abi_v1_commands_proto protoreflect.FileDescriptor

const file_abi_v1_commands_proto_rawDesc = "" +
	"\n" +
	"\x15abi/v1/commands.proto\x12\x0egocraft.abi.v1\"`\n" +
	"\vCommandTree\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x127\n" +
	"\bchildren\x18\x02 \x03(\v2\x1b.gocraft.abi.v1.CommandNodeR\bchildren\"\xaf\x04\n" +
	"\vCommandNode\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.gocraft.abi.v1.CommandNodeKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x12H\n" +
	"\rargument_type\x18\x04 \x01(\x0e2#.gocraft.abi.v1.CommandArgumentTypeR\fargumentType\x12\x1f\n" +
	"\venum_values\x18\x05 \x03(\tR\n" +
	"enumValues\x12\x1a\n" +
	"\bexecutor\x18\x06 \x01(\rR\bexecutor\x127\n" +
	"\bchildren\x18\a \x03(\v2\x1b.gocraft.abi.v1.CommandNodeR\bchildren\x12\x1f\n" +
	"\vcustom_type\x18\b \x01(\tR\n" +
	"customType\x12$\n" +
	"\vinteger_min\x18\t \x01(\x12H\x00R\n" +
	"integerMin\x88\x01\x01\x12$\n" +
	"\vinteger_max\x18\n" +
	" \x01(\x12H\x01R\n" +
	"integerMax\x88\x01\x01\x12$\n" +
	"\vdecimal_min\x18\v \x01(\x01H\x02R\n" +
	"decimalMin\x88\x01\x01\x12$\n" +
	"\vdecimal_max\x18\f \x01(\x01H\x03R\n" +
	"decimalMax\x88\x01\x01B\x0e\n" +
	"\f_integer_minB\x0e\n" +
	"\f_integer_maxB\x0e\n" +
	"\f_decimal_minB\x0e\n" +
	"\f_decimal_max*s\n" +
	"\x0fCommandNodeKind\x12!\n" +
	"\x1dCOMMAND_NODE_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_NODE_KIND_LITERAL\x10\x01\x12\x1e\n" +
	"\x1aCOMMAND_NODE_KIND_ARGUMENT\x10\x02*\xba\x03\n" +
	"\x13CommandArgumentType\x12%\n" +
	"!COMMAND_ARGUMENT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCOMMAND_ARGUMENT_TYPE_INTEGER\x10\x01\x12!\n" +
	"\x1dCOMMAND_ARGUMENT_TYPE_DECIMAL\x10\x02\x12 \n" +
	"\x1cCOMMAND_ARGUMENT_TYPE_STRING\x10\x03\x12 \n" +
	"\x1cCOMMAND_ARGUMENT_TYPE_GREEDY\x10\x04\x12 \n" +
	"\x1cCOMMAND_ARGUMENT_TYPE_PLAYER\x10\x05\x12#\n" +
	"\x1fCOMMAND_ARGUMENT_TYPE_BLOCK_POS\x10\x06\x12%\n" +
	"!COMMAND_ARGUMENT_TYPE_BLOCK_STATE\x10\a\x12\x1e\n" +
	"\x1aCOMMAND_ARGUMENT_TYPE_ITEM\x10\b\x12\"\n" +
	"\x1eCOMMAND_ARGUMENT_TYPE_DURATION\x10\t\x12\x1e\n" +
	"\x1aCOMMAND_ARGUMENT_TYPE_ENUM\x10\n" +
	"\x12 \n" +
	"\x1cCOMMAND_ARGUMENT_TYPE_CUSTOM\x10\vBX\n" +
	"\x11fr.gocraft.abi.v1B\rCommandsProtoP\x01Z2github.com/GoCraft-MC/gocraft-abi/abi/v1/wire;wireb\x06proto3"

var (
	file_abi_v1_commands_proto_rawDescOnce sync.Once
	file_abi_v1_commands_proto_rawDescData []byte
)

func file_abi_v1_commands_proto_rawDescGZIP() []byte {
	file_abi_v1_commands_proto_rawDescOnce.Do(func() {
		file_abi_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abi_v1_commands_proto_rawDesc), len(file_abi_v1_commands_proto_rawDesc)))
	})
	return file_abi_v1_commands_proto_rawDescData
}

var file_abi_v1_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_abi_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_abi_v1_commands_proto_goTypes = []any{
	(CommandNodeKind)(0),     // 0: gocraft.abi.v1.CommandNodeKind
	(CommandArgumentType)(0), // 1: gocraft.abi.v1.CommandArgumentType
	(*CommandTree)(nil),      // 2: gocraft.abi.v1.CommandTree
	(*CommandNode)(nil),      // 3: gocraft.abi.v1.CommandNode
}
var file_abi_v1_commands_proto_depIdxs = []int32{
	3, // 0: gocraft.abi.v1.CommandTree.children:type_name -> gocraft.abi.v1.CommandNode
	0, // 1: gocraft.abi.v1.CommandNode.kind:type_name -> gocraft.abi.v1.CommandNodeKind
	1, // 2: gocraft.abi.v1.CommandNode.argument_type:type_name -> gocraft.abi.v1.CommandArgumentType
	3, // 3: gocraft.abi.v1.CommandNode.children:type_name -> gocraft.abi.v1.CommandNode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_abi_v1_commands_proto_init() }
func file_abi_v1_commands_proto_init() {
	if File_abi_v1_commands_proto != nil {
		return
	}
	file_abi_v1_commands_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abi_v1_commands_proto_rawDesc), len(file_abi_v1_commands_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abi_v1_commands_proto_goTypes,
		DependencyIndexes: file_abi_v1_commands_proto_depIdxs,
		EnumInfos:         file_abi_v1_commands_proto_enumTypes,
		MessageInfos:      file_abi_v1_commands_proto_msgTypes,
	}.Build()
	File_abi_v1_commands_proto = out.File
	file_abi_v1_commands_proto_goTypes = nil
	file_abi_v1_commands_proto_depIdxs = nil
}
