// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: abi/v1/envelope.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FailurePolicy decides a cancellable event when a subscriber fails to reply in
// time. It travels with the event so the runtime can answer correctly even if
// the host has already stopped waiting.
type FailurePolicy int32

const (
	FailurePolicy_FAILURE_POLICY_UNSPECIFIED FailurePolicy = 0
	FailurePolicy_FAILURE_POLICY_ALLOW       FailurePolicy = 1
	FailurePolicy_FAILURE_POLICY_DENY        FailurePolicy = 2
)

// Enum value maps for FailurePolicy.
var (
	FailurePolicy_name = map[int32]string{
		0: "FAILURE_POLICY_UNSPECIFIED",
		1: "FAILURE_POLICY_ALLOW",
		2: "FAILURE_POLICY_DENY",
	}
	FailurePolicy_value = map[string]int32{
		"FAILURE_POLICY_UNSPECIFIED": 0,
		"FAILURE_POLICY_ALLOW":       1,
		"FAILURE_POLICY_DENY":        2,
	}
)

func (x FailurePolicy) Enum() *FailurePolicy {
	p := new(FailurePolicy)
	*p = x
	return p
}

func (x FailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_abi_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (FailurePolicy) Type() protoreflect.EnumType {
	return &file_abi_v1_envelope_proto_enumTypes[0]
}

func (x FailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicy.Descriptor instead.
func (FailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope is every message exchanged between the host and an out-of-process
// runtime. One frame carries exactly one envelope.
//
// seq correlates a reply with its request: the host registers a pending seq
// before writing and the runtime echoes it back. Messages the host does not
// wait on (READY, SHUTDOWN) may leave it at zero.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Hello
	//	*Envelope_Welcome
	//	*Envelope_Load
	//	*Envelope_Loaded
	//	*Envelope_Fail
	//	*Envelope_Ready
	//	*Envelope_Unload
	//	*Envelope_Dispatch
	//	*Envelope_Verdict
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Shutdown
	//	*Envelope_Invoke
	//	*Envelope_Invoked
	//	*Envelope_Emit
	//	*Envelope_Emitted
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_abi_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *Envelope) GetLoad() *Load {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Load); ok {
			return x.Load
		}
	}
	return nil
}

func (x *Envelope) GetLoaded() *Loaded {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Loaded); ok {
			return x.Loaded
		}
	}
	return nil
}

func (x *Envelope) GetFail() *Fail {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

func (x *Envelope) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *Envelope) GetUnload() *Unload {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Unload); ok {
			return x.Unload
		}
	}
	return nil
}

func (x *Envelope) GetDispatch() *Dispatch {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

func (x *Envelope) GetVerdict() *Verdict {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Verdict); ok {
			return x.Verdict
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *Envelope) GetInvoke() *Invoke {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

func (x *Envelope) GetInvoked() *Invoked {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Invoked); ok {
			return x.Invoked
		}
	}
	return nil
}

func (x *Envelope) GetEmit() *Emit {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Emit); ok {
			return x.Emit
		}
	}
	return nil
}

func (x *Envelope) GetEmitted() *Emitted {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Emitted); ok {
			return x.Emitted
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Hello struct {
	// Handshake. The runtime speaks first, so a version mismatch is caught
	// before the host sends anything it would have to take back.
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type Envelope_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,3,opt,name=welcome,proto3,oneof"`
}

type Envelope_Load struct {
	// Plugin lifecycle. LOAD is sequential because load order is derived from
	// the dependency graph and a plugin may rely on an earlier one.
	Load *Load `protobuf:"bytes,4,opt,name=load,proto3,oneof"`
}

type Envelope_Loaded struct {
	Loaded *Loaded `protobuf:"bytes,5,opt,name=loaded,proto3,oneof"`
}

type Envelope_Fail struct {
	Fail *Fail `protobuf:"bytes,6,opt,name=fail,proto3,oneof"`
}

type Envelope_Ready struct {
	Ready *Ready `protobuf:"bytes,7,opt,name=ready,proto3,oneof"`
}

type Envelope_Unload struct {
	Unload *Unload `protobuf:"bytes,8,opt,name=unload,proto3,oneof"`
}

type Envelope_Dispatch struct {
	// Event dispatch, the hot path.
	Dispatch *Dispatch `protobuf:"bytes,9,opt,name=dispatch,proto3,oneof"`
}

type Envelope_Verdict struct {
	Verdict *Verdict `protobuf:"bytes,10,opt,name=verdict,proto3,oneof"`
}

type Envelope_Ping struct {
	// Liveness. Three missed pongs mean the runtime is killed and respawned.
	Ping *Ping `protobuf:"bytes,11,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,12,opt,name=pong,proto3,oneof"`
}

type Envelope_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,13,opt,name=shutdown,proto3,oneof"`
}

type Envelope_Invoke struct {
	// Command invocation. Not the hot path: a person typing, at typing speed.
	Invoke *Invoke `protobuf:"bytes,14,opt,name=invoke,proto3,oneof"`
}

type Envelope_Invoked struct {
	Invoked *Invoked `protobuf:"bytes,15,opt,name=invoked,proto3,oneof"`
}

type Envelope_Emit struct {
	// A plugin-defined event, published by a plugin. The only exchange the
	// runtime starts: everything above answers something the host asked for.
	//
	// Sequence numbers are therefore split rather than shared. The host numbers
	// its requests odd and a runtime numbers its own even, so the two counters
	// cannot produce the same number and hand one side's request to a caller
	// waiting for the other's reply.
	Emit *Emit `protobuf:"bytes,16,opt,name=emit,proto3,oneof"`
}

type Envelope_Emitted struct {
	Emitted *Emitted `protobuf:"bytes,17,opt,name=emitted,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Body() {}

func (*Envelope_Welcome) isEnvelope_Body() {}

func (*Envelope_Load) isEnvelope_Body() {}

func (*Envelope_Loaded) isEnvelope_Body() {}

func (*Envelope_Fail) isEnvelope_Body() {}

func (*Envelope_Ready) isEnvelope_Body() {}

func (*Envelope_Unload) isEnvelope_Body() {}

func (*Envelope_Dispatch) isEnvelope_Body() {}

func (*Envelope_Verdict) isEnvelope_Body() {}

func (*Envelope_Ping) isEnvelope_Body() {}

func (*Envelope_Pong) isEnvelope_Body() {}

func (*Envelope_Shutdown) isEnvelope_Body() {}

func (*Envelope_Invoke) isEnvelope_Body() {}

func (*Envelope_Invoked) isEnvelope_Body() {}

func (*Envelope_Emit) isEnvelope_Body() {}

func (*Envelope_Emitted) isEnvelope_Body() {}

// Hello announces the runtime and the ABI it was built against. A mismatch
// makes the runtime exit rather than negotiate: a runtime that guesses is worse
// than one that refuses.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Abi   uint32                 `protobuf:"varint,1,opt,name=abi,proto3" json:"abi,omitempty"`
	// Human-readable, for logs only. Never parsed. e.g. "jvm 25.0.3".
	Runtime       string `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_abi_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetAbi() uint32 {
	if x != nil {
		return x.Abi
	}
	return 0
}

func (x *Hello) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

// Welcome carries the host facts a runtime needs before any plugin starts.
type Welcome struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Abi      uint32                 `protobuf:"varint,1,opt,name=abi,proto3" json:"abi,omitempty"`
	TickRate uint32                 `protobuf:"varint,2,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	// The shared budget for one cancellable event across all of its subscribers.
	// The runtime cannot enforce it, but it can log when it overruns.
	EventBudgetMs uint32 `protobuf:"varint,3,opt,name=event_budget_ms,json=eventBudgetMs,proto3" json:"event_budget_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_abi_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Welcome) GetAbi() uint32 {
	if x != nil {
		return x.Abi
	}
	return 0
}

func (x *Welcome) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *Welcome) GetEventBudgetMs() uint32 {
	if x != nil {
		return x.EventBudgetMs
	}
	return 0
}

// Load asks the runtime to bring up one plugin from an already validated
// bundle. The host has read the manifest; the runtime is told where the bundle
// is, not asked to discover it.
type Load struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PluginId   string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	BundlePath string                 `protobuf:"bytes,2,opt,name=bundle_path,json=bundlePath,proto3" json:"bundle_path,omitempty"`
	Entry      string                 `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	// Where this plugin's own files live: its configuration, unpacked from the
	// bundle's config/ on first load, and anything it writes for itself.
	//
	// The host owns it. It creates the directory, seeds the defaults and never
	// overwrites what an admin edited, so a runtime is told the path rather than
	// deriving one — two runtimes deriving it separately would eventually derive
	// it differently.
	//
	// Added in ABI 1 after the fact: a runtime built before this reads an empty
	// string, which is why nothing may assume it is set.
	DataDirectory string `protobuf:"bytes,4,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	// Where the command tree sits inside the bundle, from the manifest's
	// [commands] tree. Empty when the plugin declares no commands.
	//
	// The path, not the tree. The runtime opens this bundle anyway, and the tree
	// is what its executor ids are numbered by, so sending a copy would be a
	// second definition of it — free to disagree with the one the runtime binds
	// its handlers against. Sending the path instead is what the host already
	// does for entry: it read the manifest, so the runtime does not have to.
	CommandTree string `protobuf:"bytes,5,opt,name=command_tree,json=commandTree,proto3" json:"command_tree,omitempty"`
	// The plugin-defined event types this plugin provides or subscribes to, with
	// the id the host assigned each of them. Empty for a plugin that touches
	// none, which is every plugin until one declares [[events.provides]].
	//
	// Sent per plugin rather than once per runtime, because a runtime has no use
	// for the id of an event none of its plugins can see, and because the host
	// assigns the ids from the full set of installed manifests — a fact that is
	// only settled once every bundle has been scanned.
	EventTypes    []*EventBinding `protobuf:"bytes,6,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Load) Reset() {
	*x = Load{}
	mi := &file_abi_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Load) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load) ProtoMessage() {}

func (x *Load) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load.ProtoReflect.Descriptor instead.
func (*Load) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *Load) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Load) GetBundlePath() string {
	if x != nil {
		return x.BundlePath
	}
	return ""
}

func (x *Load) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *Load) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

func (x *Load) GetCommandTree() string {
	if x != nil {
		return x.CommandTree
	}
	return ""
}

func (x *Load) GetEventTypes() []*EventBinding {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// EventBinding is one plugin-defined event type and the number standing in for
// its name on the wire.
//
// The name and the id, and deliberately nothing else. The layout — which field
// is at which index, and what it is called — is the runtime's own: it comes
// from the class the author compiled or the table they wrote by hand, and the
// manifest is what the build compares the two against. Re-sending it here would
// be a second copy of the layout at runtime, free to disagree with the one the
// codec was generated from.
type EventBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Never zero: abi/v1 reserves 0 in Event.type_id for native events.
	TypeId uint32 `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// As a manifest spells it, e.g. "fr.oreo.shop/purchase".
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBinding) Reset() {
	*x = EventBinding{}
	mi := &file_abi_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBinding) ProtoMessage() {}

func (x *EventBinding) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBinding.ProtoReflect.Descriptor instead.
func (*EventBinding) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *EventBinding) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *EventBinding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Loaded reports what the plugin actually registered, which the host checks
// against the manifest it validated. A plugin that subscribes to an event it
// never declared is a bug, not a feature.
type Loaded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Events        []string               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loaded) Reset() {
	*x = Loaded{}
	mi := &file_abi_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loaded) ProtoMessage() {}

func (x *Loaded) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loaded.ProtoReflect.Descriptor instead.
func (*Loaded) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *Loaded) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Loaded) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

// Fail rejects one plugin without bringing the runtime down. Per-plugin failure
// is what makes an external runtime tolerable to operate.
type Fail struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PluginId string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// Meant to be shown to an admin verbatim, e.g. "config.yml:12 taxRate < 0".
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fail) Reset() {
	*x = Fail{}
	mi := &file_abi_v1_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fail) ProtoMessage() {}

func (x *Fail) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fail.ProtoReflect.Descriptor instead.
func (*Fail) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *Fail) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Fail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Ready ends the load phase. The host opens its listeners only after this.
type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_abi_v1_envelope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{7}
}

type Unload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unload) Reset() {
	*x = Unload{}
	mi := &file_abi_v1_envelope_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unload) ProtoMessage() {}

func (x *Unload) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unload.ProtoReflect.Descriptor instead.
func (*Unload) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{8}
}

func (x *Unload) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// Dispatch delivers one event to one plugin. The host, not the runtime, decides
// who receives what and in which order, because subscription order and the
// shared budget are host concerns.
type Dispatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dispatch) Reset() {
	*x = Dispatch{}
	mi := &file_abi_v1_envelope_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispatch) ProtoMessage() {}

func (x *Dispatch) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispatch.ProtoReflect.Descriptor instead.
func (*Dispatch) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{9}
}

func (x *Dispatch) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Dispatch) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_abi_v1_envelope_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{10}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_abi_v1_envelope_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{11}
}

// Shutdown asks for an orderly stop. The host still kills the process if it
// does not exit within its window.
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_abi_v1_envelope_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{12}
}

// Value is the positional value carried by events, verdicts and host calls.
//
// Positional rather than named: field names would have to match across every
// language, and renaming one would break every runtime at once. The layout is
// declared in the manifest, so both sides agree on what index 3 means without
// the wire format carrying that agreement on every event.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_BoolValue
	//	*Value_Int64Value
	//	*Value_DoubleValue
	//	*Value_StringValue
	//	*Value_BytesValue
	//	*Value_ListValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_abi_v1_envelope_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{13}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ValueList {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_ListValue struct {
	// A oneof cannot hold a repeated field, hence the wrapper.
	ListValue *ValueList `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_Int64Value) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

type ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueList) Reset() {
	*x = ValueList{}
	mi := &file_abi_v1_envelope_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueList) ProtoMessage() {}

func (x *ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueList.ProtoReflect.Descriptor instead.
func (*ValueList) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{14}
}

func (x *ValueList) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Event is the generic envelope used for both native and plugin-defined events.
// One shape for all of them means a new event costs a manifest entry, not a
// change to this schema.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Negotiated at load time for plugin-defined events, so the type string is
	// not re-sent on every dispatch. Zero for native events.
	TypeId        uint32        `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Fields        []*Value      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	OnFailure     FailurePolicy `protobuf:"varint,4,opt,name=on_failure,json=onFailure,proto3,enum=gocraft.abi.v1.FailurePolicy" json:"on_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_abi_v1_envelope_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{15}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Event) GetFields() []*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Event) GetOnFailure() FailurePolicy {
	if x != nil {
		return x.OnFailure
	}
	return FailurePolicy_FAILURE_POLICY_UNSPECIFIED
}

// Mutation replaces the value at a positional path after a subscriber runs.
// The path indexes into the event fields, so a nested value is addressed
// without the plugin sending the whole event back.
type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []uint32               `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_abi_v1_envelope_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{16}
}

func (x *Mutation) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Mutation) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// HostCall is a protocol-neutral request for a mutation or side effect. Writes
// never originate from a plugin directly: the host queues these and the
// simulation tick applies them.
type HostCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Fields        []*Value               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCall) Reset() {
	*x = HostCall{}
	mi := &file_abi_v1_envelope_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCall) ProtoMessage() {}

func (x *HostCall) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCall.ProtoReflect.Descriptor instead.
func (*HostCall) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{17}
}

func (x *HostCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HostCall) GetFields() []*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Verdict is one subscriber's answer to one event.
type Verdict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Mutations     []*Mutation            `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	Effects       []*HostCall            `protobuf:"bytes,3,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_abi_v1_envelope_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{18}
}

func (x *Verdict) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *Verdict) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *Verdict) GetEffects() []*HostCall {
	if x != nil {
		return x.Effects
	}
	return nil
}

// Invoke runs one command executor in the runtime that loaded it.
//
// The host has already parsed the line against the command tree the bundle
// shipped, resolved every argument to a value of the declared type, and checked
// the permissions guarding the path to this executor. The runtime is handed the
// result; it never sees the raw line and never parses one. Two runtimes parsing
// the same grammar would eventually parse it differently, and the tree is the
// host's to enforce because the host is what offers completions to a client.
type Invoke struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PluginId string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// The executor field of the CommandNode this invocation reached.
	Executor      uint32             `protobuf:"varint,2,opt,name=executor,proto3" json:"executor,omitempty"`
	Sender        *CommandSender     `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Arguments     []*CommandArgument `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoke) Reset() {
	*x = Invoke{}
	mi := &file_abi_v1_envelope_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoke) ProtoMessage() {}

func (x *Invoke) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoke.ProtoReflect.Descriptor instead.
func (*Invoke) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{19}
}

func (x *Invoke) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Invoke) GetExecutor() uint32 {
	if x != nil {
		return x.Executor
	}
	return 0
}

func (x *Invoke) GetSender() *CommandSender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Invoke) GetArguments() []*CommandArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CommandSender is whoever typed the command.
type CommandSender struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The PlayerRef vocabulary type: uuid, username, edition. An empty list means
	// there is no player behind this — the console, or a command block — which is
	// a normal case a handler has to expect, not an error.
	Player *Value `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	// Display name, for a handler that wants to name the sender in its reply.
	// The console has one and no player, which is why this is not read off the
	// PlayerRef.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Every permission node the plugin's manifest declared, resolved for this
	// sender, as [node, allowed] pairs.
	//
	// Injected for the same reason events inject theirs: the envelope has no
	// message for asking, so can() is only answerable because the answer arrived
	// with the request. Unlike an event this costs nothing to over-supply — one
	// resolution per command typed, not per block broken.
	Permissions   []*Value `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSender) Reset() {
	*x = CommandSender{}
	mi := &file_abi_v1_envelope_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSender) ProtoMessage() {}

func (x *CommandSender) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSender.ProtoReflect.Descriptor instead.
func (*CommandSender) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{20}
}

func (x *CommandSender) GetPlayer() *Value {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *CommandSender) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSender) GetPermissions() []*Value {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// CommandArgument is one parsed argument.
//
// Named, where an event's fields are positional. An event's layout is declared
// once in the manifest and read on every dispatch, so paying for names there
// would be paying on the hot path for something both sides already agree on.
// A command executor's arguments are whatever the path through the tree
// collected, so a runtime would have to walk its own copy of the tree to
// recover the order — the same derivation written once per language, free to
// drift. The name is cheaper than the drift.
type CommandArgument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// What the host parsed it as, so a handler asking for the wrong type is
	// refused by the runtime rather than reading a zero value.
	Type          CommandArgumentType `protobuf:"varint,2,opt,name=type,proto3,enum=gocraft.abi.v1.CommandArgumentType" json:"type,omitempty"`
	Value         *Value              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandArgument) Reset() {
	*x = CommandArgument{}
	mi := &file_abi_v1_envelope_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandArgument) ProtoMessage() {}

func (x *CommandArgument) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandArgument.ProtoReflect.Descriptor instead.
func (*CommandArgument) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{21}
}

func (x *CommandArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandArgument) GetType() CommandArgumentType {
	if x != nil {
		return x.Type
	}
	return CommandArgumentType_COMMAND_ARGUMENT_TYPE_UNSPECIFIED
}

func (x *CommandArgument) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Emit publishes a plugin-defined event and waits for what the subscribers did
// to it. Runtime → host, the one exchange a runtime starts.
//
// The host owns the dispatch for the same reason it owns native events:
// subscribers span runtimes, they run in priority order, and cancellation has
// to be arbitrated by something that is not one of them.
type Emit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Who is emitting. The host skips this plugin's own subscribers — a plugin
	// hearing its own event back would double-count it, and §10 makes the
	// emitter's copy of the object the thing the mutations are replayed into.
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// From the EventBinding table this plugin was loaded with.
	TypeId uint32 `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// Positional, in the order the manifest declares. No names: the layout is
	// agreed at build time, so paying for names here would be paying per emit for
	// something both sides already know.
	Fields        []*Value `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emit) Reset() {
	*x = Emit{}
	mi := &file_abi_v1_envelope_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emit) ProtoMessage() {}

func (x *Emit) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emit.ProtoReflect.Descriptor instead.
func (*Emit) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{22}
}

func (x *Emit) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Emit) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Emit) GetFields() []*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Emitted answers one Emit. Host → runtime, correlated by the seq the runtime
// chose.
type Emitted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means the event was dispatched. Anything else is a fault in the
	// emitting plugin — an unknown type id, or a type it does not provide — and
	// is reported rather than fatal: one plugin's bug must not take down the
	// runtime its neighbours are living in.
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// A subscriber cancelled, or a fail-closed event lost one. The emitter is
	// expected to abandon whatever it was about to do.
	Cancelled bool `protobuf:"varint,2,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	// What the subscribers changed, as a diff against the fields that were sent.
	// The runtime replays these into the emitter's own object, which is what
	// makes a cross-process, cross-language dispatch feel in-process.
	Mutations     []*Mutation `protobuf:"bytes,3,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emitted) Reset() {
	*x = Emitted{}
	mi := &file_abi_v1_envelope_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emitted) ProtoMessage() {}

func (x *Emitted) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emitted.ProtoReflect.Descriptor instead.
func (*Emitted) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{23}
}

func (x *Emitted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Emitted) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *Emitted) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

// Invoked answers one Invoke. It carries no plugin id: like Verdict, it is
// correlated by seq.
type Invoked struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means the command succeeded. Anything else is shown to the sender and
	// logged, so it is written for a person: "no region named spawn", not a stack
	// trace.
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Everything the handler asked the world to do, including replying to the
	// sender. A command handler runs in another process and must not write to the
	// world from there, so it queues the same host calls a verdict does and the
	// tick applies them.
	Effects       []*HostCall `protobuf:"bytes,2,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoked) Reset() {
	*x = Invoked{}
	mi := &file_abi_v1_envelope_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoked) ProtoMessage() {}

func (x *Invoked) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_envelope_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoked.ProtoReflect.Descriptor instead.
func (*Invoked) Descriptor() ([]byte, []int) {
	return file_abi_v1_envelope_proto_rawDescGZIP(), []int{24}
}

func (x *Invoked) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Invoked) GetEffects() []*HostCall {
	if x != nil {
		return x.Effects
	}
	return nil
}

var File_abi_v1_envelope_proto protoreflect.FileDescriptor

const file_abi_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x15abi/v1/envelope.proto\x12\x0egocraft.abi.v1\x1a\x15abi/v1/commands.proto\"\xb8\x06\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12-\n" +
	"\x05hello\x18\x02 \x01(\v2\x15.gocraft.abi.v1.HelloH\x00R\x05hello\x123\n" +
	"\awelcome\x18\x03 \x01(\v2\x17.gocraft.abi.v1.WelcomeH\x00R\awelcome\x12*\n" +
	"\x04load\x18\x04 \x01(\v2\x14.gocraft.abi.v1.LoadH\x00R\x04load\x120\n" +
	"\x06loaded\x18\x05 \x01(\v2\x16.gocraft.abi.v1.LoadedH\x00R\x06loaded\x12*\n" +
	"\x04fail\x18\x06 \x01(\v2\x14.gocraft.abi.v1.FailH\x00R\x04fail\x12-\n" +
	"\x05ready\x18\a \x01(\v2\x15.gocraft.abi.v1.ReadyH\x00R\x05ready\x120\n" +
	"\x06unload\x18\b \x01(\v2\x16.gocraft.abi.v1.UnloadH\x00R\x06unload\x126\n" +
	"\bdispatch\x18\t \x01(\v2\x18.gocraft.abi.v1.DispatchH\x00R\bdispatch\x123\n" +
	"\averdict\x18\n" +
	" \x01(\v2\x17.gocraft.abi.v1.VerdictH\x00R\averdict\x12*\n" +
	"\x04ping\x18\v \x01(\v2\x14.gocraft.abi.v1.PingH\x00R\x04ping\x12*\n" +
	"\x04pong\x18\f \x01(\v2\x14.gocraft.abi.v1.PongH\x00R\x04pong\x126\n" +
	"\bshutdown\x18\r \x01(\v2\x18.gocraft.abi.v1.ShutdownH\x00R\bshutdown\x120\n" +
	"\x06invoke\x18\x0e \x01(\v2\x16.gocraft.abi.v1.InvokeH\x00R\x06invoke\x123\n" +
	"\ainvoked\x18\x0f \x01(\v2\x17.gocraft.abi.v1.InvokedH\x00R\ainvoked\x12*\n" +
	"\x04emit\x18\x10 \x01(\v2\x14.gocraft.abi.v1.EmitH\x00R\x04emit\x123\n" +
	"\aemitted\x18\x11 \x01(\v2\x17.gocraft.abi.v1.EmittedH\x00R\aemittedB\x06\n" +
	"\x04body\"3\n" +
	"\x05Hello\x12\x10\n" +
	"\x03abi\x18\x01 \x01(\rR\x03abi\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\"`\n" +
	"\aWelcome\x12\x10\n" +
	"\x03abi\x18\x01 \x01(\rR\x03abi\x12\x1b\n" +
	"\ttick_rate\x18\x02 \x01(\rR\btickRate\x12&\n" +
	"\x0fevent_budget_ms\x18\x03 \x01(\rR\reventBudgetMs\"\xe3\x01\n" +
	"\x04Load\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vbundle_path\x18\x02 \x01(\tR\n" +
	"bundlePath\x12\x14\n" +
	"\x05entry\x18\x03 \x01(\tR\x05entry\x12%\n" +
	"\x0edata_directory\x18\x04 \x01(\tR\rdataDirectory\x12!\n" +
	"\fcommand_tree\x18\x05 \x01(\tR\vcommandTree\x12=\n" +
	"\vevent_types\x18\x06 \x03(\v2\x1c.gocraft.abi.v1.EventBindingR\n" +
	"eventTypes\";\n" +
	"\fEventBinding\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\rR\x06typeId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"=\n" +
	"\x06Loaded\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\";\n" +
	"\x04Fail\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\a\n" +
	"\x05Ready\"%\n" +
	"\x06Unload\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"T\n" +
	"\bDispatch\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12+\n" +
	"\x05event\x18\x02 \x01(\v2\x15.gocraft.abi.v1.EventR\x05event\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"\n" +
	"\n" +
	"\bShutdown\"\xfc\x01\n" +
	"\x05Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12:\n" +
	"\n" +
	"list_value\x18\x06 \x01(\v2\x19.gocraft.abi.v1.ValueListH\x00R\tlistValueB\x06\n" +
	"\x04kind\":\n" +
	"\tValueList\x12-\n" +
	"\x06values\x18\x01 \x03(\v2\x15.gocraft.abi.v1.ValueR\x06values\"\xa1\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\rR\x06typeId\x12-\n" +
	"\x06fields\x18\x03 \x03(\v2\x15.gocraft.abi.v1.ValueR\x06fields\x12<\n" +
	"\n" +
	"on_failure\x18\x04 \x01(\x0e2\x1d.gocraft.abi.v1.FailurePolicyR\tonFailure\"K\n" +
	"\bMutation\x12\x12\n" +
	"\x04path\x18\x01 \x03(\rR\x04path\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.gocraft.abi.v1.ValueR\x05value\"M\n" +
	"\bHostCall\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\x06fields\x18\x02 \x03(\v2\x15.gocraft.abi.v1.ValueR\x06fields\"\x93\x01\n" +
	"\aVerdict\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x126\n" +
	"\tmutations\x18\x02 \x03(\v2\x18.gocraft.abi.v1.MutationR\tmutations\x122\n" +
	"\aeffects\x18\x03 \x03(\v2\x18.gocraft.abi.v1.HostCallR\aeffects\"\xb7\x01\n" +
	"\x06Invoke\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1a\n" +
	"\bexecutor\x18\x02 \x01(\rR\bexecutor\x125\n" +
	"\x06sender\x18\x03 \x01(\v2\x1d.gocraft.abi.v1.CommandSenderR\x06sender\x12=\n" +
	"\targuments\x18\x04 \x03(\v2\x1f.gocraft.abi.v1.CommandArgumentR\targuments\"\x8b\x01\n" +
	"\rCommandSender\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.gocraft.abi.v1.ValueR\x06player\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\vpermissions\x18\x03 \x03(\v2\x15.gocraft.abi.v1.ValueR\vpermissions\"\x8b\x01\n" +
	"\x0fCommandArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.gocraft.abi.v1.CommandArgumentTypeR\x04type\x12+\n" +
	"\x05value\x18\x03 \x01(\v2\x15.gocraft.abi.v1.ValueR\x05value\"k\n" +
	"\x04Emit\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\rR\x06typeId\x12-\n" +
	"\x06fields\x18\x03 \x03(\v2\x15.gocraft.abi.v1.ValueR\x06fields\"u\n" +
	"\aEmitted\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1c\n" +
	"\tcancelled\x18\x02 \x01(\bR\tcancelled\x126\n" +
	"\tmutations\x18\x03 \x03(\v2\x18.gocraft.abi.v1.MutationR\tmutations\"S\n" +
	"\aInvoked\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x122\n" +
	"\aeffects\x18\x02 \x03(\v2\x18.gocraft.abi.v1.HostCallR\aeffects*b\n" +
	"\rFailurePolicy\x12\x1e\n" +
	"\x1aFAILURE_POLICY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FAILURE_POLICY_ALLOW\x10\x01\x12\x17\n" +
	"\x13FAILURE_POLICY_DENY\x10\x02BX\n" +
	"\x11fr.gocraft.abi.v1B\rEnvelopeProtoP\x01Z2github.com/GoCraft-MC/gocraft-abi/abi/v1/wire;wireb\x06proto3"

var (
	file_abi_v1_envelope_proto_rawDescOnce sync.Once
	file_abi_v1_envelope_proto_rawDescData []byte
)

func file_abi_v1_envelope_proto_rawDescGZIP() []byte {
	file_abi_v1_envelope_proto_rawDescOnce.Do(func() {
		file_abi_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abi_v1_envelope_proto_rawDesc), len(file_abi_v1_envelope_proto_rawDesc)))
	})
	return file_abi_v1_envelope_proto_rawDescData
}

var file_abi_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_abi_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_abi_v1_envelope_proto_goTypes = []any{
	(FailurePolicy)(0),       // 0: gocraft.abi.v1.FailurePolicy
	(*Envelope)(nil),         // 1: gocraft.abi.v1.Envelope
	(*Hello)(nil),            // 2: gocraft.abi.v1.Hello
	(*Welcome)(nil),          // 3: gocraft.abi.v1.Welcome
	(*Load)(nil),             // 4: gocraft.abi.v1.Load
	(*EventBinding)(nil),     // 5: gocraft.abi.v1.EventBinding
	(*Loaded)(nil),           // 6: gocraft.abi.v1.Loaded
	(*Fail)(nil),             // 7: gocraft.abi.v1.Fail
	(*Ready)(nil),            // 8: gocraft.abi.v1.Ready
	(*Unload)(nil),           // 9: gocraft.abi.v1.Unload
	(*Dispatch)(nil),         // 10: gocraft.abi.v1.Dispatch
	(*Ping)(nil),             // 11: gocraft.abi.v1.Ping
	(*Pong)(nil),             // 12: gocraft.abi.v1.Pong
	(*Shutdown)(nil),         // 13: gocraft.abi.v1.Shutdown
	(*Value)(nil),            // 14: gocraft.abi.v1.Value
	(*ValueList)(nil),        // 15: gocraft.abi.v1.ValueList
	(*Event)(nil),            // 16: gocraft.abi.v1.Event
	(*Mutation)(nil),         // 17: gocraft.abi.v1.Mutation
	(*HostCall)(nil),         // 18: gocraft.abi.v1.HostCall
	(*Verdict)(nil),          // 19: gocraft.abi.v1.Verdict
	(*Invoke)(nil),           // 20: gocraft.abi.v1.Invoke
	(*CommandSender)(nil),    // 21: gocraft.abi.v1.CommandSender
	(*CommandArgument)(nil),  // 22: gocraft.abi.v1.CommandArgument
	(*Emit)(nil),             // 23: gocraft.abi.v1.Emit
	(*Emitted)(nil),          // 24: gocraft.abi.v1.Emitted
	(*Invoked)(nil),          // 25: gocraft.abi.v1.Invoked
	(CommandArgumentType)(0), // 26: gocraft.abi.v1.CommandArgumentType
}
var file_abi_v1_envelope_proto_depIdxs = []int32{
	2,  // 0: gocraft.abi.v1.Envelope.hello:type_name -> gocraft.abi.v1.Hello
	3,  // 1: gocraft.abi.v1.Envelope.welcome:type_name -> gocraft.abi.v1.Welcome
	4,  // 2: gocraft.abi.v1.Envelope.load:type_name -> gocraft.abi.v1.Load
	6,  // 3: gocraft.abi.v1.Envelope.loaded:type_name -> gocraft.abi.v1.Loaded
	7,  // 4: gocraft.abi.v1.Envelope.fail:type_name -> gocraft.abi.v1.Fail
	8,  // 5: gocraft.abi.v1.Envelope.ready:type_name -> gocraft.abi.v1.Ready
	9,  // 6: gocraft.abi.v1.Envelope.unload:type_name -> gocraft.abi.v1.Unload
	10, // 7: gocraft.abi.v1.Envelope.dispatch:type_name -> gocraft.abi.v1.Dispatch
	19, // 8: gocraft.abi.v1.Envelope.verdict:type_name -> gocraft.abi.v1.Verdict
	11, // 9: gocraft.abi.v1.Envelope.ping:type_name -> gocraft.abi.v1.Ping
	12, // 10: gocraft.abi.v1.Envelope.pong:type_name -> gocraft.abi.v1.Pong
	13, // 11: gocraft.abi.v1.Envelope.shutdown:type_name -> gocraft.abi.v1.Shutdown
	20, // 12: gocraft.abi.v1.Envelope.invoke:type_name -> gocraft.abi.v1.Invoke
	25, // 13: gocraft.abi.v1.Envelope.invoked:type_name -> gocraft.abi.v1.Invoked
	23, // 14: gocraft.abi.v1.Envelope.emit:type_name -> gocraft.abi.v1.Emit
	24, // 15: gocraft.abi.v1.Envelope.emitted:type_name -> gocraft.abi.v1.Emitted
	5,  // 16: gocraft.abi.v1.Load.event_types:type_name -> gocraft.abi.v1.EventBinding
	16, // 17: gocraft.abi.v1.Dispatch.event:type_name -> gocraft.abi.v1.Event
	15, // 18: gocraft.abi.v1.Value.list_value:type_name -> gocraft.abi.v1.ValueList
	14, // 19: gocraft.abi.v1.ValueList.values:type_name -> gocraft.abi.v1.Value
	14, // 20: gocraft.abi.v1.Event.fields:type_name -> gocraft.abi.v1.Value
	0,  // 21: gocraft.abi.v1.Event.on_failure:type_name -> gocraft.abi.v1.FailurePolicy
	14, // 22: gocraft.abi.v1.Mutation.value:type_name -> gocraft.abi.v1.Value
	14, // 23: gocraft.abi.v1.HostCall.fields:type_name -> gocraft.abi.v1.Value
	17, // 24: gocraft.abi.v1.Verdict.mutations:type_name -> gocraft.abi.v1.Mutation
	18, // 25: gocraft.abi.v1.Verdict.effects:type_name -> gocraft.abi.v1.HostCall
	21, // 26: gocraft.abi.v1.Invoke.sender:type_name -> gocraft.abi.v1.CommandSender
	22, // 27: gocraft.abi.v1.Invoke.arguments:type_name -> gocraft.abi.v1.CommandArgument
	14, // 28: gocraft.abi.v1.CommandSender.player:type_name -> gocraft.abi.v1.Value
	14, // 29: gocraft.abi.v1.CommandSender.permissions:type_name -> gocraft.abi.v1.Value
	26, // 30: gocraft.abi.v1.CommandArgument.type:type_name -> gocraft.abi.v1.CommandArgumentType
	14, // 31: gocraft.abi.v1.CommandArgument.value:type_name -> gocraft.abi.v1.Value
	14, // 32: gocraft.abi.v1.Emit.fields:type_name -> gocraft.abi.v1.Value
	17, // 33: gocraft.abi.v1.Emitted.mutations:type_name -> gocraft.abi.v1.Mutation
	18, // 34: gocraft.abi.v1.Invoked.effects:type_name -> gocraft.abi.v1.HostCall
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_abi_v1_envelope_proto_init() }
func file_abi_v1_envelope_proto_init() {
	if File_abi_v1_envelope_proto != nil {
		return
	}
	file_abi_v1_commands_proto_init()
	file_abi_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Welcome)(nil),
		(*Envelope_Load)(nil),
		(*Envelope_Loaded)(nil),
		(*Envelope_Fail)(nil),
		(*Envelope_Ready)(nil),
		(*Envelope_Unload)(nil),
		(*Envelope_Dispatch)(nil),
		(*Envelope_Verdict)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Shutdown)(nil),
		(*Envelope_Invoke)(nil),
		(*Envelope_Invoked)(nil),
		(*Envelope_Emit)(nil),
		(*Envelope_Emitted)(nil),
	}
	file_abi_v1_envelope_proto_msgTypes[13].OneofWrappers = []any{
		(*Value_BoolValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_ListValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abi_v1_envelope_proto_rawDesc), len(file_abi_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abi_v1_envelope_proto_goTypes,
		DependencyIndexes: file_abi_v1_envelope_proto_depIdxs,
		EnumInfos:         file_abi_v1_envelope_proto_enumTypes,
		MessageInfos:      file_abi_v1_envelope_proto_msgTypes,
	}.Build()
	File_abi_v1_envelope_proto = out.File
	file_abi_v1_envelope_proto_goTypes = nil
	file_abi_v1_envelope_proto_depIdxs = nil
}
