// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: abi/v1/events.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerRef struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Uuid     []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// "java" or "bedrock". A plugin should rarely care, and the one place it
	// does is deciding what a client can render.
	Edition       string `protobuf:"bytes,3,opt,name=edition,proto3" json:"edition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRef) Reset() {
	*x = PlayerRef{}
	mi := &file_abi_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRef) ProtoMessage() {}

func (x *PlayerRef) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRef.ProtoReflect.Descriptor instead.
func (*PlayerRef) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerRef) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *PlayerRef) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerRef) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

type BlockPos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"zigzag64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"zigzag64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             int64                  `protobuf:"zigzag64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPos) Reset() {
	*x = BlockPos{}
	mi := &file_abi_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPos) ProtoMessage() {}

func (x *BlockPos) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPos.ProtoReflect.Descriptor instead.
func (*BlockPos) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *BlockPos) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BlockPos) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BlockPos) GetZ() int64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespaced, as the registries spell it: "minecraft:oak_stairs".
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The full state rather than a handle to re-resolve. A handler that had to
	// ask the server what it was just given would pay a round trip inside an
	// event that is blocking the tick.
	Properties    map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_abi_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type BlockBreak struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Player *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Pos    *BlockPos              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Block  *Block                 `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	// The item in hand, namespaced. Empty when breaking bare-handed.
	Tool string `protobuf:"bytes,4,opt,name=tool,proto3" json:"tool,omitempty"`
	// Resolved by the host before dispatch, for every node the manifest
	// subscribed to. A handler asking about one never pays a round trip — which
	// matters because it is holding the tick while it asks.
	Perms         map[string]bool `protobuf:"bytes,5,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockBreak) Reset() {
	*x = BlockBreak{}
	mi := &file_abi_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockBreak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBreak) ProtoMessage() {}

func (x *BlockBreak) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBreak.ProtoReflect.Descriptor instead.
func (*BlockBreak) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *BlockBreak) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *BlockBreak) GetPos() *BlockPos {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *BlockBreak) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockBreak) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *BlockBreak) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,2,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_abi_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerJoin) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerJoin) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

// Fired only after a valid placement has been computed, before any block or
// item changes. Multi-block structures produce one event for the primary block.
type BlockPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Pos           *BlockPos              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Block         *Block                 `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	Replaced      *Block                 `protobuf:"bytes,4,opt,name=replaced,proto3" json:"replaced,omitempty"`
	Dimension     int64                  `protobuf:"zigzag64,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,6,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPlace) Reset() {
	*x = BlockPlace{}
	mi := &file_abi_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPlace) ProtoMessage() {}

func (x *BlockPlace) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPlace.ProtoReflect.Descriptor instead.
func (*BlockPlace) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *BlockPlace) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *BlockPlace) GetPos() *BlockPos {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *BlockPlace) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockPlace) GetReplaced() *Block {
	if x != nil {
		return x.Replaced
	}
	return nil
}

func (x *BlockPlace) GetDimension() int64 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *BlockPlace) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

type PlayerQuit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerQuit) Reset() {
	*x = PlayerQuit{}
	mi := &file_abi_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQuit) ProtoMessage() {}

func (x *PlayerQuit) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQuit.ProtoReflect.Descriptor instead.
func (*PlayerQuit) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerQuit) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerQuit) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// The unformatted chat text, before broadcasting. A rewritten message is
// never reinterpreted as a command.
type PlayerChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,3,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerChat) Reset() {
	*x = PlayerChat{}
	mi := &file_abi_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerChat) ProtoMessage() {}

func (x *PlayerChat) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerChat.ProtoReflect.Descriptor instead.
func (*PlayerChat) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerChat) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerChat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlayerChat) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

// Permissions and argument parsing run AFTER plugins rewrite the command.
type PlayerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,3,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCommand) Reset() {
	*x = PlayerCommand{}
	mi := &file_abi_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCommand) ProtoMessage() {}

func (x *PlayerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCommand.ProtoReflect.Descriptor instead.
func (*PlayerCommand) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerCommand) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PlayerCommand) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

// Damage entering the player's health pipeline, before resistance and
// absorption. Armour already applied by the caller is not applied again.
type PlayerDamage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Damage        float64                `protobuf:"fixed64,2,opt,name=damage,proto3" json:"damage,omitempty"`
	Cause         string                 `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,4,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDamage) Reset() {
	*x = PlayerDamage{}
	mi := &file_abi_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDamage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDamage) ProtoMessage() {}

func (x *PlayerDamage) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDamage.ProtoReflect.Descriptor instead.
func (*PlayerDamage) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerDamage) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerDamage) GetDamage() float64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *PlayerDamage) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *PlayerDamage) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

type PlayerDeath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Cause         string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDeath) Reset() {
	*x = PlayerDeath{}
	mi := &file_abi_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDeath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDeath) ProtoMessage() {}

func (x *PlayerDeath) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDeath.ProtoReflect.Descriptor instead.
func (*PlayerDeath) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerDeath) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerDeath) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

// Notification after a dead player has successfully respawned.
type PlayerRespawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
	Dimension     int64                  `protobuf:"zigzag64,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRespawn) Reset() {
	*x = PlayerRespawn{}
	mi := &file_abi_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRespawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRespawn) ProtoMessage() {}

func (x *PlayerRespawn) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRespawn.ProtoReflect.Descriptor instead.
func (*PlayerRespawn) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerRespawn) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerRespawn) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerRespawn) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerRespawn) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerRespawn) GetDimension() int64 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

type PlayerTeleport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	FromX         float64                `protobuf:"fixed64,2,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"`
	FromY         float64                `protobuf:"fixed64,3,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	FromZ         float64                `protobuf:"fixed64,4,opt,name=from_z,json=fromZ,proto3" json:"from_z,omitempty"`
	X             float64                `protobuf:"fixed64,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,6,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,7,opt,name=z,proto3" json:"z,omitempty"`
	Dimension     int64                  `protobuf:"zigzag64,8,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,9,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTeleport) Reset() {
	*x = PlayerTeleport{}
	mi := &file_abi_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTeleport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTeleport) ProtoMessage() {}

func (x *PlayerTeleport) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTeleport.ProtoReflect.Descriptor instead.
func (*PlayerTeleport) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerTeleport) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerTeleport) GetFromX() float64 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *PlayerTeleport) GetFromY() float64 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *PlayerTeleport) GetFromZ() float64 {
	if x != nil {
		return x.FromZ
	}
	return 0
}

func (x *PlayerTeleport) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerTeleport) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerTeleport) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerTeleport) GetDimension() int64 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *PlayerTeleport) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

// An attempted main-hand block/entity interaction. Cancelling prevents the
// associated use/boarding/trade action; it does not describe an attack.
type PlayerInteract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Pos           *BlockPos              `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	EntityId      int64                  `protobuf:"zigzag64,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Item          string                 `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	Dimension     int64                  `protobuf:"zigzag64,6,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,7,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInteract) Reset() {
	*x = PlayerInteract{}
	mi := &file_abi_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInteract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInteract) ProtoMessage() {}

func (x *PlayerInteract) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInteract.ProtoReflect.Descriptor instead.
func (*PlayerInteract) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerInteract) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerInteract) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PlayerInteract) GetPos() *BlockPos {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlayerInteract) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *PlayerInteract) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *PlayerInteract) GetDimension() int64 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *PlayerInteract) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

// Java container clicks and Bedrock normal inventory transactions. Slot -1
// means an edition's transaction spans several slots rather than one click.
type InventoryClick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Slot          int64                  `protobuf:"zigzag64,3,opt,name=slot,proto3" json:"slot,omitempty"`
	Button        int64                  `protobuf:"zigzag64,4,opt,name=button,proto3" json:"button,omitempty"`
	Mode          int64                  `protobuf:"zigzag64,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,6,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryClick) Reset() {
	*x = InventoryClick{}
	mi := &file_abi_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryClick) ProtoMessage() {}

func (x *InventoryClick) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryClick.ProtoReflect.Descriptor instead.
func (*InventoryClick) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *InventoryClick) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *InventoryClick) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *InventoryClick) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *InventoryClick) GetButton() int64 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *InventoryClick) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *InventoryClick) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

// A use-in-air item action, not use-on-block or inventory movement.
type ItemUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerRef             `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Hand          int64                  `protobuf:"zigzag64,3,opt,name=hand,proto3" json:"hand,omitempty"`
	Perms         map[string]bool        `protobuf:"bytes,4,rep,name=perms,proto3" json:"perms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUse) Reset() {
	*x = ItemUse{}
	mi := &file_abi_v1_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUse) ProtoMessage() {}

func (x *ItemUse) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUse.ProtoReflect.Descriptor instead.
func (*ItemUse) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{15}
}

func (x *ItemUse) GetPlayer() *PlayerRef {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *ItemUse) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *ItemUse) GetHand() int64 {
	if x != nil {
		return x.Hand
	}
	return 0
}

func (x *ItemUse) GetPerms() map[string]bool {
	if x != nil {
		return x.Perms
	}
	return nil
}

// Non-player entity damage. Players use player.damage, never both events.
type EntityDamage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"zigzag64,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Damage        float64                `protobuf:"fixed64,3,opt,name=damage,proto3" json:"damage,omitempty"`
	Cause         string                 `protobuf:"bytes,4,opt,name=cause,proto3" json:"cause,omitempty"`
	Dimension     int64                  `protobuf:"zigzag64,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDamage) Reset() {
	*x = EntityDamage{}
	mi := &file_abi_v1_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDamage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDamage) ProtoMessage() {}

func (x *EntityDamage) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDamage.ProtoReflect.Descriptor instead.
func (*EntityDamage) Descriptor() ([]byte, []int) {
	return file_abi_v1_events_proto_rawDescGZIP(), []int{16}
}

func (x *EntityDamage) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityDamage) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityDamage) GetDamage() float64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *EntityDamage) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *EntityDamage) GetDimension() int64 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

var File_abi_v1_events_proto protoreflect.FileDescriptor

const file_abi_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x13abi/v1/events.proto\x12\x0egocraft.abi.v1\x1a\x14abi/v1/options.proto\"U\n" +
	"\tPlayerRef\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x18\n" +
	"\aedition\x18\x03 \x01(\tR\aedition\"4\n" +
	"\bBlockPos\x12\f\n" +
	"\x01x\x18\x01 \x01(\x12R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x12R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x12R\x01z\"\x9d\x01\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2%.gocraft.abi.v1.Block.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\n" +
	"BlockBreak\x121\n" +
	"\x06player\x18\x01 \x01(\v2\x19.gocraft.abi.v1.PlayerRefR\x06player\x12*\n" +
	"\x03pos\x18\x02 \x01(\v2\x18.gocraft.abi.v1.BlockPosR\x03pos\x12+\n" +
	"\x05block\x18\x03 \x01(\v2\x15.gocraft.abi.v1.BlockR\x05block\x12\x12\n" +
	"\x04tool\x18\x04 \x01(\tR\x04tool\x12A\n" +
	"\x05perms\x18\x05 \x03(\v2%.gocraft.abi.v1.BlockBreak.PermsEntryB\x04\x90\xb5\x18\x01R\x05perms\x1a8\n" +
	"\n" +
	"PermsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01:\"\x8a\xb5\x18\x1e\n" +
	"\vblock.break\x10\x01\x18\x01 \x01*\amessage0\x01\"\xde\x01\n" +
	"\n" +
	"PlayerJoin\x121\n" +
	"\x06player\x18\x01 \x01(\v2\x19.gocraft.abi.v1.PlayerRefR\x06player\x12A\n" +
	"\x05perms\x18\x02 \x03(\v2%.gocraft.abi.v1.PlayerJoin.PermsEntryB\x04\x90\xb5\x18\x01R\x05perms\x1a8\n" +
	"\n" +
	"PermsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01: \x8a\xb5\x18\x1c\n" +
	"\vplayer.join\x18\x02 \x01*\amessage0\x01BV\n" +
	"\x11fr.gocraft.abi.v1B\vEventsProtoP\x01Z2github.com/GoCraft-MC/gocraft-abi/abi/v1/wire;wireb\x06proto3"

var (
	file_abi_v1_events_proto_rawDescOnce sync.Once
	file_abi_v1_events_proto_rawDescData []byte
)

func file_abi_v1_events_proto_rawDescGZIP() []byte {
	file_abi_v1_events_proto_rawDescOnce.Do(func() {
		file_abi_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abi_v1_events_proto_rawDesc), len(file_abi_v1_events_proto_rawDesc)))
	})
	return file_abi_v1_events_proto_rawDescData
}

var file_abi_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_abi_v1_events_proto_goTypes = []any{
	(*PlayerRef)(nil),  // 0: gocraft.abi.v1.PlayerRef
	(*BlockPos)(nil),   // 1: gocraft.abi.v1.BlockPos
	(*Block)(nil),      // 2: gocraft.abi.v1.Block
	(*BlockBreak)(nil), // 3: gocraft.abi.v1.BlockBreak
	(*PlayerJoin)(nil), // 4: gocraft.abi.v1.PlayerJoin
	nil,                // 5: gocraft.abi.v1.Block.PropertiesEntry
	nil,                // 6: gocraft.abi.v1.BlockBreak.PermsEntry
	nil,                // 7: gocraft.abi.v1.PlayerJoin.PermsEntry
}
var file_abi_v1_events_proto_depIdxs = []int32{
	5, // 0: gocraft.abi.v1.Block.properties:type_name -> gocraft.abi.v1.Block.PropertiesEntry
	0, // 1: gocraft.abi.v1.BlockBreak.player:type_name -> gocraft.abi.v1.PlayerRef
	1, // 2: gocraft.abi.v1.BlockBreak.pos:type_name -> gocraft.abi.v1.BlockPos
	2, // 3: gocraft.abi.v1.BlockBreak.block:type_name -> gocraft.abi.v1.Block
	6, // 4: gocraft.abi.v1.BlockBreak.perms:type_name -> gocraft.abi.v1.BlockBreak.PermsEntry
	0, // 5: gocraft.abi.v1.PlayerJoin.player:type_name -> gocraft.abi.v1.PlayerRef
	7, // 6: gocraft.abi.v1.PlayerJoin.perms:type_name -> gocraft.abi.v1.PlayerJoin.PermsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_abi_v1_events_proto_init() }
func file_abi_v1_events_proto_init() {
	if File_abi_v1_events_proto != nil {
		return
	}
	file_abi_v1_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abi_v1_events_proto_rawDesc), len(file_abi_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abi_v1_events_proto_goTypes,
		DependencyIndexes: file_abi_v1_events_proto_depIdxs,
		MessageInfos:      file_abi_v1_events_proto_msgTypes,
	}.Build()
	File_abi_v1_events_proto = out.File
	file_abi_v1_events_proto_goTypes = nil
	file_abi_v1_events_proto_depIdxs = nil
}
