// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: abi/v1/options.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	// The tick waits for every subscriber, under one budget shared by all of
	// them. This is what lets a plugin prevent something.
	Phase_PHASE_TICK_BLOCKING Phase = 1
	// Dispatched and forgotten. The tick never waits, so a slow subscriber costs
	// nothing and cancelling means nothing.
	Phase_PHASE_OBSERVATIONAL Phase = 2
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_TICK_BLOCKING",
		2: "PHASE_OBSERVATIONAL",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":   0,
		"PHASE_TICK_BLOCKING": 1,
		"PHASE_OBSERVATIONAL": 2,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_abi_v1_options_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_abi_v1_options_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_abi_v1_options_proto_rawDescGZIP(), []int{0}
}

type EventOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name the manifest subscribes to, and the only identity that crosses
	// the wire for a native event: "block.break", "player.join".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Whether a subscriber can prevent it. A cancellable event blocks the tick;
	// an observational one is fire-and-forget.
	Cancellable bool  `protobuf:"varint,2,opt,name=cancellable,proto3" json:"cancellable,omitempty"`
	Phase       Phase `protobuf:"varint,3,opt,name=phase,proto3,enum=gocraft.abi.v1.Phase" json:"phase,omitempty"`
	// What the event resolves to when a subscriber fails to answer in time. It
	// travels with the event so a runtime can answer correctly even after the
	// host has stopped waiting.
	//
	// Reused from envelope.proto rather than redeclared: proto3 scopes enum
	// values to the package, not the enum, so a second FailurePolicy here would
	// not merely risk drifting from that one — it would fail to compile against
	// it.
	OnFailure FailurePolicy `protobuf:"varint,4,opt,name=on_failure,json=onFailure,proto3,enum=gocraft.abi.v1.FailurePolicy" json:"on_failure,omitempty"`
	// Side effects a handler may request, batched into the verdict rather than
	// sent one at a time — which is what keeps one event to one round trip.
	// Only the effects named here appear on the generated event class.
	Effects []string `protobuf:"bytes,5,rep,name=effects,proto3" json:"effects,omitempty"`
	// The ABI version that introduced this event. The generator emits it, and a
	// runtime built against an older ABI refuses to load the plugin with a
	// message rather than failing on first dispatch.
	Since         uint32 `protobuf:"varint,6,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	mi := &file_abi_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_abi_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_abi_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *EventOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventOptions) GetCancellable() bool {
	if x != nil {
		return x.Cancellable
	}
	return false
}

func (x *EventOptions) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *EventOptions) GetOnFailure() FailurePolicy {
	if x != nil {
		return x.OnFailure
	}
	return FailurePolicy_FAILURE_POLICY_UNSPECIFIED
}

func (x *EventOptions) GetEffects() []string {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *EventOptions) GetSince() uint32 {
	if x != nil {
		return x.Since
	}
	return 0
}

var file_abi_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventOptions)(nil),
		Field:         50001,
		Name:          "gocraft.abi.v1.event",
		Tag:           "bytes,50001,opt,name=event",
		Filename:      "abi/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "gocraft.abi.v1.injected",
		Tag:           "varint,50002,opt,name=injected",
		Filename:      "abi/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional gocraft.abi.v1.EventOptions event = 50001;
	E_Event = &file_abi_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool injected = 50002;
	E_Injected = &file_abi_v1_options_proto_extTypes[1]
)

var File_abi_v1_options_proto protoreflect.FileDescriptor

const file_abi_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x14abi/v1/options.proto\x12\x0egocraft.abi.v1\x1a google/protobuf/descriptor.proto\x1a\x15abi/v1/envelope.proto\"\xdf\x01\n" +
	"\fEventOptions\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vcancellable\x18\x02 \x01(\bR\vcancellable\x12+\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x15.gocraft.abi.v1.PhaseR\x05phase\x12<\n" +
	"\n" +
	"on_failure\x18\x04 \x01(\x0e2\x1d.gocraft.abi.v1.FailurePolicyR\tonFailure\x12\x18\n" +
	"\aeffects\x18\x05 \x03(\tR\aeffects\x12\x14\n" +
	"\x05since\x18\x06 \x01(\rR\x05since*P\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PHASE_TICK_BLOCKING\x10\x01\x12\x17\n" +
	"\x13PHASE_OBSERVATIONAL\x10\x02:U\n" +
	"\x05event\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x1c.gocraft.abi.v1.EventOptionsR\x05event:;\n" +
	"\binjected\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\binjectedBW\n" +
	"\x11fr.gocraft.abi.v1B\fOptionsProtoP\x01Z2github.com/GoCraft-MC/gocraft-abi/abi/v1/wire;wireb\x06proto3"

var (
	file_abi_v1_options_proto_rawDescOnce sync.Once
	file_abi_v1_options_proto_rawDescData []byte
)

func file_abi_v1_options_proto_rawDescGZIP() []byte {
	file_abi_v1_options_proto_rawDescOnce.Do(func() {
		file_abi_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abi_v1_options_proto_rawDesc), len(file_abi_v1_options_proto_rawDesc)))
	})
	return file_abi_v1_options_proto_rawDescData
}

var file_abi_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_abi_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_abi_v1_options_proto_goTypes = []any{
	(Phase)(0),                          // 0: gocraft.abi.v1.Phase
	(*EventOptions)(nil),                // 1: gocraft.abi.v1.EventOptions
	(FailurePolicy)(0),                  // 2: gocraft.abi.v1.FailurePolicy
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_abi_v1_options_proto_depIdxs = []int32{
	0, // 0: gocraft.abi.v1.EventOptions.phase:type_name -> gocraft.abi.v1.Phase
	2, // 1: gocraft.abi.v1.EventOptions.on_failure:type_name -> gocraft.abi.v1.FailurePolicy
	3, // 2: gocraft.abi.v1.event:extendee -> google.protobuf.MessageOptions
	4, // 3: gocraft.abi.v1.injected:extendee -> google.protobuf.FieldOptions
	1, // 4: gocraft.abi.v1.event:type_name -> gocraft.abi.v1.EventOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_abi_v1_options_proto_init() }
func file_abi_v1_options_proto_init() {
	if File_abi_v1_options_proto != nil {
		return
	}
	file_abi_v1_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abi_v1_options_proto_rawDesc), len(file_abi_v1_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_abi_v1_options_proto_goTypes,
		DependencyIndexes: file_abi_v1_options_proto_depIdxs,
		EnumInfos:         file_abi_v1_options_proto_enumTypes,
		MessageInfos:      file_abi_v1_options_proto_msgTypes,
		ExtensionInfos:    file_abi_v1_options_proto_extTypes,
	}.Build()
	File_abi_v1_options_proto = out.File
	file_abi_v1_options_proto_goTypes = nil
	file_abi_v1_options_proto_depIdxs = nil
}
